### ISSUE TITLE
segment fault 

### ISSUE THREAD

**Issue by jinyucn** [phananh1010/PanoSalNet#1]
When I run the code, it implies the segment fault after network initialization. So, how can I solve it？Thanks.

**Comment by phananh1010** [comment]
It is hard to say without full error logs, can you provide?

**Comment by jinyucn** [comment]
Thanks for your replay, I met a new problem as illustrated below when running panosalnet.py.

I1024 19:04:57.612540   818 net.cpp:242] This network produces output loss
I1024 19:04:57.612561   818 net.cpp:255] Network initialization done.
F1024 19:04:57.614075   818 upgrade_proto.cpp:97] Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: panosalnet_iter_800.caffemodel
*** Check failure stack trace: ***
Aborted (core dumped)

My device information include Ubuntu, gtx 1050ti, 10G, Caffe, python3.5.

**Comment by phananh1010** [comment]
Hi jinyucn, have you download the parameter file "panosalnet_iter_800.caffemodel"?  You may change the path in the .prototxt file and point to the model file.

**Comment by phananh1010** [comment]
If you have further questions, please open a new issue.
