### ISSUE TITLE
Questions about fps

### ISSUE THREAD

**Issue by htc220** [phananh1010/PanoSalNet#2]
I found that the frame rate you set is 30, I want to know how to set it when the frame rate is 24？

**Comment by phananh1010** [comment]
I did not see the problem with fps, can you elaborate the question?

**Comment by htc220** [comment]
> I did not see the problem with fps, can you elaborate the question?
I want to generate a saliency map frame by frame on my data set, but my video’s frame rate is 24. I noticed that your saliency map is generated according to the timestamp, and the frame rate is 30, is it just modified like this:
get_fixation.py:     https://github.com/phananh1010/PanoSaliency/blob/d67f0abbf323b2c6f98dfbf3055968bc802ab026/get_fixation.py#L15
line 15:DELTA -> 1.0/24
line 43:for t in np.arange(0, vlength, DELTA):

**Comment by phananh1010** [comment]
I see, the code you are viewing generate ground truth saliency map from head movement log. Specify a timestamp, it will find the closest head movement data within a threshold. Modifying DELTA as you suggested is a correct way.

**Comment by htc220** [comment]
Thank you very much!

**Comment by htc220** [comment]
In addition, I am also very interested in the part of your head movement prediction. I want to add more data dimensions, but when training with pytorch, I don’t know how to input so many features into it. Could you share the training code to us?

**Comment by phananh1010** [comment]
I don't have immediate access to the training code for the head prediction model now, unfortunately. However, the idea is to flatten all features and concatenate them together.

**Comment by htc220** [comment]
Thank you for your guidance!
