### ISSUE TITLE
Questions about evaluation

### ISSUE THREAD

**Issue by htc220** [phananh1010/PanoSalNet#3]
Sorry to bother you again. In the prediction accuracy section, did you set a threshold to determine which tiles will be viewed, or directly expand the field of view with the largest fixation point?

**Comment by phananh1010** [comment]
I directly expand around the tile with highest salient value.

**Comment by htc220** [comment]
Thank you very much！

**Comment by htc220** [comment]
So when you calculate the accuracy， did you expand around the tile with highest salient value like 5x5 tiles and compare with the ground truth tiles（5x5 tiles as fov）？

**Comment by htc220** [comment]
So when you calculate the accuracy， did you expand around the tile with highest salient value like 5x5 tiles as prediction and compare with the ground truth tiles（5x5 tiles as fov）？

**Comment by phananh1010** [comment]
Yes. For the tile size, please check our paper for the value that we used.

**Comment by htc220** [comment]
Thanks，we noted that some papers use Multi-label classification model but we are confused about the input orientation。Now we use 9x16 tiles as you do instead， and I want to  use the tile with max value as fixation and consider the bipolar changes.

**Comment by htc220** [comment]
Thanks，we noted that you use 9x16 tiles as a frame，but gaussian gblur_size you use is 5, so I think that the fov size of yours is 5 pixel. But I am confused about how to calculation the accuracy.Because each tile you predict is a value but I am confused how many tiles do you choose as predict tiles......Do you mean that you use the tile with max value as fixation and choose the tiles around it as predicted tiles?

**Comment by phananh1010** [comment]
The accuracy we used is the number of overlapping tiles between predicted & ground truth divided to the total number of tiles.

**Comment by htc220** [comment]
Can you tell me how to calculate the overlapping? Do you use thresholds to determine which tiles will be viewed and then calculate the overlapping?

**Comment by htc220** [comment]
Could you tell me how to calculate the overlapping? Do you use thresholds to determine which tiles will be viewed and then calculate the overlapping?

**Comment by phananh1010** [comment]
No, overlapping just means position of the predicted tiles are the same with ground truth tiles. Then, only ground truth tiles are actually viewed by users, since they are ground truth.

**Comment by htc220** [comment]
Oh，I see！Thank you very much！

**Comment by htc220** [comment]
I have another qustion: This image is your prediction at a time, but I am confused about how to decide the predicted fov.Does it mean if the values does not equals to the ground truth values in the same tile, it will be True?
![image](https://user-images.githubusercontent.com/39826671/87807107-6ee89600-c88a-11ea-871f-75246e0fe9ec.png)

**Comment by phananh1010** [comment]
To get predicted tiles, select the tile with the highest value and then all the tile around it. It should be the tiles completely inside the red rectangle in your image.

**Comment by htc220** [comment]
I see！Thank you very much！^_^
