### ISSUE TITLE
About sds and series

### ISSUE THREAD

**Issue by EricPengShuai** [phananh1010/PanoSalNet#4]
Hello,
1. Are sds file and series file generated from [salient_ds_dict_w16_h9](https://www.dropbox.com/s/r09s1yqr2qyluyr/salient_ds.zip?dl=0)?
2. Why is the shape of sds (794, 9, 16) ? (series.shape = (794, 3)）What does the first dimension 794 represent?
---
1. In addition, after I input a video frame, can I get its corresponding **saliency map** through the [panosalnet.py](https://github.com/phananh1010/PanoSalNet/blob/master/panosalnet.py) script ?
2. Where is the default prediction window k set？
Thanks!

**Comment by phananh1010** [comment]
Hello,
sds and series file are processed input from saliency maps and head orientation. sds is a list of saliency maps scaled down to 9x16. The time distance between two consecutive maps are 0.06 seconds.

For additional question,
1. Yes, the purpose of panosalnet is to generate saliency map from input image.
2. The default prediction windows is 0.5 seconds.

**Comment by EricPengShuai** [comment]
> Hello,
> sds and series file are processed input from saliency maps and head orientation. sds is a list of saliency maps scaled down to 9x16. The time distance between two consecutive maps are 0.06 seconds.
> 
> For additional question,
> 
> 1. Yes, the purpose of panosalnet is to generate saliency map from input image.
> 2. The default prediction windows is 0.5 seconds.

1. Does the file named [salient_ds_dict_w16_h9](https://www.dropbox.com/s/r09s1yqr2qyluyr/salient_ds.zip?dl=0) you put in the dropbox include saliency maps and head orientation?
2. In your [lstm](https://github.com/phananh1010/PanoSalNet/blob/master/lstm.py) code, what variable do you use to set the prediction window?
Thanks!

**Comment by phananh1010** [comment]
For (2), you can check the look_ahead variable, which has the value of 8, meaning looking 8 frame ahead. Distance between two consecutive frames are 0.06 seconds.

For (1), what do you need it for? It is not mentioned in the Github Readme, so it will take long time to dig up.

**Comment by EricPengShuai** [comment]
@phananh1010 Excuse me, I want to know if the following function in [get_list.py](https://github.com/phananh1010/PanoSalNet/blob/master/get_qlist.py) is used to calculate the head direction at a certain moment based on the quaternion in the csv file
https://github.com/phananh1010/PanoSalNet/blob/c1294c8a7e9226226788c94c6a1f231ff627b2e3/get_qlist.py#L156
I am curious why it is not written like this in the order of (w, x, y, z)，[reference](http://kieranwynn.github.io/pyquaternion/#object-initialisation)
```Python
v = extract_direction(Quaternion([item[5], item[2], item[3], item[4]]), v0=[0, 0, 1])
```
<img src="https://i.loli.net/2021/06/16/aDnuGLmdNJ1xToI.png" style="zoom: 40%"/>

**Comment by phananh1010** [comment]
It is because different system has different way to represent the coordinate systems. I changed the order so that all different systems were mapped into my coordinate system.
