### ISSUE TITLE
About model in panosalnet_test.prototxt

### ISSUE THREAD

**Issue by EricPengShuai** [phananh1010/PanoSalNet#5]
Hello , @phananh1010 
Your paper says that the first three-layer structure in the PanSalNet network is the same as VGGNet, but it is not written like this in your panosalnet_test.prototxt.

Would you please tell me in detail how you initialized this network called PanSalNet before training.

Thanks!
EricPengShuai

**Comment by phananh1010** [comment]
Hello, 
panosalnet_test.prototxt. is just the metadata file specifying the network structure. Please check for the code to transfer network parameters in Caffee

**Comment by EricPengShuai** [comment]
@phananh1010 Do you mean the file called panosalnet.py? But I find that this is just to load the parameters that have been trained.

**Comment by phananh1010** [comment]
Yes, the weights loaded by our model is the result of training on ImageNet (first two layers), and SALICON (the later layers). We will continue train on our own dataset after that.
